added alt text to images on create map page
WildAid/wildaid.github.io pull request #119
Opened 2020-10-15 14:05 UTC by Augs0

## Related Issue
#73

Fixes #
Added alt text for all images on the Create Map page

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://bit.ly/ofishsandbox) or a [local build](https://wildaid.github.io/build).

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here**

2020-10-19 13:05 UTC, Sheeri requested changes
Hello! In the first alt tag, there is a spelling mistake:
coordiantes
should be
coordinates

Otherwise, these are great alt tags - thank you! Please make the requested change and push to this branch, the PR will automatically update, and then I can approve it.

2020-10-21 07:12 UTC, Augs0 commented
Thank you for your feedback :) this should be all fixed now

2020-10-22 13:38 UTC, Sheeri approved these changes

2020-10-22 13:38 UTC, merged

2020-10-22 13:38 UTC, Sheeri commented
Perfect!

Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.